; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; Select exactly one 'Arduino' sketch directory as the main .ino entry point!
src_dir = src/Qbead_MDP

[env:seeed_xiao_nrf52840_sense]
; Beware! Not explicitly pinned so external updates could induce build errors
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840
framework = arduino
monitor_speed = 9600
; Known issue for nrf52 frameworks not finding this correct compiled lib
build_flags =
  -I $PROJECT_PACKAGES_DIR/framework-arduinoadafruitnrf52/libraries/Adafruit_TinyUSB_Arduino/src
lib_deps = 
	adafruit/Adafruit NeoPixel
	seeed-studio/Seeed Arduino LSM6DS3